//
// Created by Mert Biyikli on 23.06.26.
//

#ifndef OBLIVIOUSROUTING_TYPES_H
#define OBLIVIOUSROUTING_TYPES_H

enum class SolverType {
    ELECTRICAL_NAIVE,
    ELECTRICAL_SKETCHING,
    RAECKE_FRT_FLAT,
    RAECKE_CKR_FLAT,
    RAECKE_RANDOM_MST_FLAT,
    RAECKE_FRT_MENDELSCALING_FLAT,
    RAECKE_CKR_MENDELSCALING_FLAT,
    LP_APPLEGATE_COHEN,
    ELECTRICAL_PARALLEL_BATCHES,
    RAECKE_FRT_POINTER,
    RAECKE_CKR_POINTER,
    RAECKE_RANDOM_MST_POINTER,
    RAECKE_FRT_MENDELSCALING_POINTER,
    RAECKE_CKR_MENDELSCALING_POINTER,
    SEMI_ELECTRICAL,
    SEMI_TREE,
    EXPANDER_HIERARCHY,
    SEMI_EXPANDER_HIERARCHY,
    EXPANDER_MWU
};

enum class DemandModelType {
    GRAVITY,
    BIMODAL,
    GAUSSIAN,
    UNIFORM,
    NONE
};

enum class GraphFormat {
    CSR,
    ADJLIST
};


enum class OutputFormat {
    TEXT,
    JSON,
    COUT
};

enum class ResultStatus {
    OK,
    ERROR_INVALID_SOLVER,
    ERROR_INVALID_ROUTING_SCHEME,
    ERROR_MISSING_DEMAND_MODELS,
    ERROR_EXCEPTION
};


#endif //OBLIVIOUSROUTING_TYPES_H