//
// Created by Mert Biyikli on 23.06.26.
//

#ifndef OBLIVIOUSROUTING_TYPES_H
#define OBLIVIOUSROUTING_TYPES_H

enum class SolverType {
    ELECTRICAL_NAIVE,
    ELECTRICAL_SKETCHING,
    RAECKE_FRT_FLAT,
    RAECKE_CKR_FLAT,
    RAECKE_RANDOM_MST_FLAT,
    RAECKE_FRT_MENDELSCALING_FLAT,
    RAECKE_CKR_MENDELSCALING_FLAT,
    LP_APPLEGATE_COHEN,
    ELECTRICAL_PARALLEL_BATCHES,
    RAECKE_FRT_POINTER,
    RAECKE_CKR_POINTER,
    RAECKE_RANDOM_MST_POINTER,
    RAECKE_FRT_MENDELSCALING_POINTER,
    RAECKE_CKR_MENDELSCALING_POINTER,
    SEMI_ELECTRICAL,
    SEMI_TREE
};

#endif //OBLIVIOUSROUTING_TYPES_H