FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ORTOOLS_ROOT=/usr/local

RUN apt-get update && apt-get install -y \
    git cmake build-essential ninja-build \
    libz-dev libbz2-dev libeigen3-dev \
    libgmp-dev \
    libboost-all-dev \
    libboost-program-options-dev \
    libboost-serialization-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ddemidov/amgcl.git --depth 1 /tmp/amgcl && \
    cmake -S /tmp/amgcl -B /tmp/amgcl/build -DCMAKE_INSTALL_PREFIX=/usr/local && \
    cmake --install /tmp/amgcl/build && \
    rm -rf /tmp/amgcl

RUN git clone https://github.com/google/or-tools.git --branch v9.6 --depth 1 /tmp/or-tools && \
    cmake -S /tmp/or-tools -B /tmp/ortools-build -G Ninja \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_DEPS=ON \
      -DBUILD_SAMPLES=OFF && \
    cmake --build /tmp/ortools-build -j"$(nproc)" && \
    cmake --install /tmp/ortools-build --prefix /usr/local && \
    rm -rf /tmp/or-tools /tmp/ortools-build